apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TZlbyZscJz05zkgOY/NrnmKtA2R/BSh/+M4qSSLE+ml8zpcwnpWjrg==,iv:aQpc2+Vy/WQoz8IU39MYjS7H2tQY7cSoALFRzkDgywM=,tag:yaBD5qJqxyoqNVFAUZ5VEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R1dLRjQyc1MvanIzeFhn
            N08wOTBlc2UyNUJvRDVqT0JRbC9RUmtsZ1NZCjY4RXNsWmZjeU1xTG5oQUNzSnhU
            ZTFXMU5WSk9FSHE1NmdIS0ZGcm1wMEEKLS0tIENyWGJEVk16L2l0MDA4SUhlT3ln
            VnJaekZLWHlvYUxFSC83WHc1a0UvbXcK4qX8nlEeAYd+bYi04EbeGu/myM6IKWQi
            4inOooiJvOmtBscDIVVS6NBSyaOIdsMzbO0jV+oNnP1zwgSvNbbPAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T12:34:35Z"
    mac: ENC[AES256_GCM,data:MYgrrfU9Qgde95SImCgXHlk4LIYD9LwZKt+qCBjKLwS+x9Ppj5qw2xOc8h0T7rr+4R3UmEvommpX5BSv7/Ih7pNI7NNwDpl0IfpAhb9z7T/+XndU91YYmV/dmjPbdDFa0oWDV3nVPJzUibHBCMjBFqtNBZsoOJMNxBnk8hcuCtM=,iv:Npb2qJuI+lAldQ+bgH9EBv0CsOXSec/Jpx6MdNzsE6I=,tag:5Jyims8/b1ECaRjCllQppg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
