apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QQanQwhIYIQ+82EQHYzeV+9g7u7Moe/1k6OHc/Buw8sMMBpt5SbUzA==,iv:+94Bo2J7J7NlH68MNo5qaADljpgKt8/4sbY8ZD56zY0=,tag:YsXa3pgmyMqsEaCwVVBZuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK0hvZ3RpU2Zod3FVWVpS
            MzZjUXRISWhKeGNMQVd0N1dJcjhnempWMEZ3CmhHMXVkWkhSQmMxWW1lTmQ5Uldx
            ZFpGOXR4NnV1RG9US1lyU2U5cVRYaUEKLS0tIFNXQVhkVHlGaURDRW5mVVpYMUow
            RW5UWHlKU2tNWDZxZnQ0U3V1ZlcyVXMKCmdL9jzLpnJlgAveauEpdsNViN7HkM1E
            HJXKRfAtaItloT3kn3XU0c/MmuWVTeSueOS/EEBIHj4rv/FpSB3soQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T12:28:33Z"
    mac: ENC[AES256_GCM,data:vBNiWENHgHiTZPQeLT4Pd/hne/k+NuXP6NQedagIzLNCtHHG1rXvqCBIRPh2NoP3jpDt8uK/x//J9tgmJuinOHG4xyVwc/VKUwvKexkI7qK/ZbTQU8nUg4fWdcKZDaUFns5VmWKbOKtJ9b9zgwxbyss1aF6SoN7flveSfbdCCGY=,iv:J8MUZaIejFAVjWd2d1T0rHH+H+oYJBrqA1QP80yxrwA=,tag:ffeH++AMezrL8m3vksvYNQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
