apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Jpp2HNhKc1toazL4Gd5yzvmcSTfPmzf7Ef+jyP7TFlCfQDybbfRfGw==,iv:vZgAXTrohjGWDJ9sr17rqJVdj5Yz6KxXo7Oi8slAMoU=,tag:tl880EbgJH4KBJihArLF3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGczZpdHR3ZkZuT2VKM2VY
            Q2tseC9RL1k1VnE4ekVkU1FEMFExNjBFZXljCkJOMjdwRmplclpFZkRQRFB2Uktx
            N21rMHZ4R3JwbnYzdjNTL3BjZDF2cWcKLS0tIFhTSkF6dVNUWUlqRWwxZFNESzNT
            OG5qaXQ4WjA2NXJ1M21rMHZkZkkrVlUKUqbVPOLSycFFo8GGHezOvJJ4XQivbC+C
            sYvDSYyXjyNiiNLS9yNB2638BNWpOxYsmQ8mElzpd8ctLnt8h6SNrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-01T09:48:30Z"
    mac: ENC[AES256_GCM,data:h1wVa0cNKlAKkYcA3JX6Eh5A4MWeoXtBl8k8a9faWQPTQ7jGHFdCTtvPbtcjDbrd3IW7QKyzj5YArEPmOdQDeyRpn9Cieb9zfg+8rMMLSUy84JeHV2UbOVKEBNsEjtNvhKDm7W2xDLzSZhl8Sz5kY3ecve5og4C2joz4keiZHrU=,iv:40gZ/CE8EflfbpGNHKZD/scGahN/tofZHtuqnkcsdkE=,tag:L95hQZzI2o0+Klr3wMfKIA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
