apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qd9AdcXQbYwm7s2AnQsfGUf/2hWnr15Usk7e8zzqAJhf8HygLJ9Q8V4fy8a+1RmNzB+zCylw/yLvutOt9vFrpuBk/YnnrCvmzHB0Y+KbP9X/gYjnqCcV519f0OB6PLR40hAGB4swnSCQkbqwiJN+ak3+25bODPk1pyCVW9MkNHrsosMPzNWO8+voPfK8oy6xWItidM1j3Qnsd2DQQx44ek3cZN/GckyNbYDIpUdLHiMETrDB5tLqzVfbuMUNED+PLG1DeBb8nxP4gwQOv/TTQZQCZHuScBOgdTa3u4DoRIQhZDEuNJKXk56yQVZxLtAPNW+BhJVhdcTAGYH5oyptBpT9ML1KVWw5NS0lVafa5/z1I359tHi71ohfWbW77HW8,iv:t2IQO+o8blpMr9CupdW2mbs9JWRSxbDxVKJyFoXOyqs=,tag:6jeJ4CQvnCXPWxNRUHUT0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:Coe3udaNlHD8cupWncnSIFCsU608V96o7AC4148dgJO5Kk2vJIBB8C18X3ejELyotVb6QiHyaKDut8dm0OR5RAP9z0GA2UyQe3Wyh1KUzSXyQ7XgPmTvviCvKtq1HEXVax8r9dn28MbmBf6iakwIxKPRNJVclMQXkEnO90h622lzMHJSYfHPyc0dYB9i6aeFuSfzVdRVx3+/cRFrbldkChM1gabcuYkFE54gXZk68pVGzfs6DPuW4meaFPmfA/5PiC+NbaLXO4q2erdmmw==,iv:tUUfg+28RxIhjwm7T22882bvJwDHK5NL3hS628ioOz4=,tag:aGwvWS95q5ehnyrHzsDTQw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BACpNOOy1VEiyiKMjf5MoGSGFup3uPIoOSW3ly+2WpHH/WQzUdpzBy5TszM8tPdTewSOH+MWAQT+fMNSZYH2Gl6Sn1inGFozVTEaHmS+uLIsr7hWorPxeMNsB4yXy/PDNy+IA9VYXgD2OeX0QkdkR8DKmgB4ousFfGnRc/Vy/CJ1vmofA7jb4H+beUI/LPxRHycdCNAWwbDSFKcLXR7YqM1fIyy0FadUYBKN,iv:nXBr2nOetJo30QY/dG6Co4j70staA/HHa7CKq+4bEYA=,tag:KjJmIIfySQzLePFvr1BfHQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MTM5eitiUUhWVUlVakRX
            TXdMbDJUdWlvTFJmRTZKOFZMNzNEQTExOHhBCmRqNm9LcGprZjUrLzlKZHM4MGhx
            YXB2cXBzSUZrVjA2SnM3NW1aTk85VDQKLS0tIFpTZ2xkaXgwZ1FPOExKejRWMHpv
            d3hCdXBOdHd5dGVkZXF1NmVFQTltbG8KMG/qtHgUxn1Ldy00Av457tk2tc8pHjsg
            4djXINPCNfz8QB0AKLP3JkDYzLALAveXe7C8DffEXElxj7Z+A4qP/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T06:56:42Z"
    mac: ENC[AES256_GCM,data:Ea6NRubDLzGy7EM+owEShT3r8iHPeDat8Dm9bfeTQ6AM5EDf3bqzpMBzsE9Hx8B0VDY/Jw6wE45H/vR/RkzbjO1QEZ23ejI39UqhNuYOJoTfNClHaxmRwzKnJ39TiHHQ5TZIlhK5jtR9Vk5OzFLY7NRgMWhDz0eIYypTd3GB234=,iv:6V6ulcMVOpjtmLFrs0cmXACrN28C+Gz7bCF/dJ1w/mo=,tag:ArTWsts+bnqpAPMBhxPA4A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
