apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HBPfMhKY7FocY6D4RoYr77hxRaqW1OaSCV8EDJgG+NUhr8bFUZHr2fjQHuyHhiAzeEsLvZtzEHSDwan4o8R5ZAoRrb3Wx4FCgfyMY1TArhpnFbaYU703GizUt0DgAz0+BBS7io5qTkZPZBthRHSmg17W3uJhRakP/6rZ6OcjQwpDEAFMsLv/r8D/TV3T0p+hvCMmutM7oesJD6XYHj+R3qTqZT7wyWdgq+maeq4sx1SUe3TezDOVDC//FdAc5Wq/OoC+S9fP+AUxrDQyMDvXYLaFUQ/ton3MSOy3pG2wmRsLeruvbe4i0oD/I4zqTEZaNI6NB44wgUlzFzDM52+S4B1jj1GUaewDPIx1590xSubZplPwsZqTw7ZsyOw9i10a,iv:8x1UaGRKY5WA5RE403xnCeIdz2PY2B5tfGTQz6FzpDU=,tag:D9yGDaX9ozqLkySZOfgazg==,type:str]
    identity.pub: ENC[AES256_GCM,data:KLdcYL2Z1UiPYiq14Ro1WTRRBb26GCVbYm/4SNs2ddxxR62RuVuDfhUb66mtnP6kdM6wJrgNCcHpGM9SrcyBzknD3kGwFsmJ0wIKEOLzK/oGV2gjTjAAtZ27ZHr5W9IjvdV0IHgAw0xwvo20dot45LVad2PdKg+pT8JVHyoeUdttABxM9v1drGaJhFbM0v0NKIW2tiPlv5XNpKY5+8AlaSps9mMpI/kfMHVXrYcNlTKVmhjGK5MqM1FCesbxq9hjdtQrsJ9oiwbPrEIf3w==,iv:eVszEWsTsMefPBnQHjn6OoQ/75EYXp31evdUanju2Ts=,tag:AntTO67mROAy8qX/TjrFnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:306G8B9xbAxNcw5QhoKRIo/nUmKtUJqHspvQ4JCsMgfVN0tnNG5/5iCPC8/upRfoF1r2K+LL3c1+be/Ba732eA19x6YuR78RBHFrcxR1ZSAVYLSFtrR+hQ9b8esTe0FeuvNgyrhF3sqb7MFF5LalQvyslaYWSK3sk30qPbCB6kZttH+x65mmYfk2Jhk4M+oa5a1eev3n7M6IVbAauTJAmuye99gv6potr9UX,iv:ogees85Xu1TEI+7lSQQiPqDNRBrxw+UY2hTZ/qScQcE=,tag:npLK0iwKGgCoMClVlGFgSQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2YxVDNkdXB0TmUyZy9O
            Y2tIeW5xRGEzYW5SNWlrd21nQmZLbUJWckdFClkvVUxLUDJKNUM4blUrOFVnT0JL
            L21Ka0dVdElGUmFrNG91b3BIUkRrQ28KLS0tIDFmaUsvNGx0SGlvbW15bGt3SG9Y
            MjF5TEJmZm9ibkNnM0RxYVNIMFhxVk0K6vxjwohjdAF5UgQqSBoUhosL6izHgJu+
            lqhHLjaEN4wK3ZO/zOnHMyjHHYXaISBegREDIFNn07JLvm485P6AlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-10T10:30:55Z"
    mac: ENC[AES256_GCM,data:i4DW45/rLb9B4o1RJUCkkMVeB2sy+Zpj4ZVdaB4aBfkwuKj5iq44hKYXXW2XZUC/OVbR+DghZ7wIcH2xTWC7k7wCz0db2MVuF6dx53EhB6A7FLMhrVSdSNT8FcHvUqxXELExub0QdvfA6bXhvlJM9oobRZlGhvKFEzqGX0DRApQ=,iv:7ST/T2ENWdGfWkWSSCfs1vw84MmxsBuhql0+ed33tOI=,tag:NnU2bl1h4i25x3hLR4up6Q==,type:str]
    shamir_threshold: 3
    version: 3.13.1
