apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LIaNUKolKx1eB18mtqCtXFomE8Mu0+KTMJzvO/iX4Fo/nt4SPZ/4AC/dGSz5xUJwD8RN2xPUl0D5kV3OA26nbXtYXxVLhaIQOfqpq8rvzGm362xSRt/YaN8G4AXg2O/3loItseCcK6Lxn5eHNg4AjCRNDu+h7RMqdCUzp9tEqhGnlUWTNBTWVvuj43GRTebHChU0PH0VnQAHGImNdQbr6lic9UzNePklMH5KVKX5KNP+Uajjrd12EZa9yCNTuOem58AjyfihT7imbEgwgRH4Q/A21FEE0SDlZc+84hCmurmUFoxOJAGnxps9Bekp02pZqovZA6qJrC0rv43q6DG0fQ1iL/yY0jS0aAe8D2FVxo5Wstc9tiarYIM5T389R137,iv:hT+7obP/piLjC7SzMjAf7kpxw6OmFsjldsL8FVOGQpo=,tag:fzg1FcWzJDB/2fbooO1LCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:QVG59fqMpxDR4mG79bim/0uBecax1zv8LcfKs+g3QknvOzAKSy0qNQGITnGXBav6p1z411baJoS7CVOTGXb0tJSHbiZ6dRTnH9BMpYOnu+K0zSJzVLSBljdFkZrLu/baoo1y/V/CMLcIavDwEibm+qUdFbir1qTPjP0DmMTfwuJSby1rojCLvwC+z3KRNvDUD+SzWFDn0cz2i1j/lscRp8V5UaZqj27SoEkkK/R+czAtfIGJRCoaqKKMorKBppHmeFzbi70uV9Ny+XqxJA==,iv:q0knZutCcRCcdgA2//1PeXPLpkyFbg98pBbzaSP/iYM=,tag:tyOJTbi3BxWblXX2JzD/yg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2KGIK26C/X7Yhse8bJEkJ6zTm6yArK15uff3YDQXH7IUWrgOEqWM8A4kFzIMrOt6zGGFDmNVFP53bQGtsme6Ji5hSMjr6AG2S4VncdHJ1VsvNRTlDRbfkkxwEXF/YzQ9udNdRvciExSHO4ZYvZ2berO6SIAukWaY/xM7+vhMkhQGABZuzhz/xdsWEmYY9CdhMEH9lNkatRZTvTWq/pno86jHOAy4XUcij0y0,iv:T70ehJ+iPPShKy3xTxEfFjWnl3BQOs104HpZsxqDbIM=,tag:HNkLv2D7jVaoani/p3o8ew==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUjJmejlnTnNFUk4wbE15
            em80SWJWT1dPRFMzelN6MHVsdExNM2NrbkdRCkJQUEI0b3pJYzkxUEdMK08va0VL
            RkRPcG42VnloS2RKb2p1YjFyTWNrcWMKLS0tIExsS2pMSUx2VDlrT3hEUjl6Y3lH
            OUxCODZRZzk3K3B2MVhrUGFiQWE5YlkK+8cTUvydoVlIeHc0qlywOiUgBwNdHNL1
            kgMMCdAECVSySqJ7QuI15fK5nAitaoc1QUE3TzAp26DnWU5hBtVVpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lyy3t8ym85ld226wgf6lnm0j7qax007a7lxsz5392jcmnnu5v6sv4kd3p
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-23T08:26:35Z"
    mac: ENC[AES256_GCM,data:axZb0JH6BEXcRpqoWIX50F0hxEG+u3eWNDcz7dWRzf65GY92DhlT7ZKSrpyeigSyrwS4tj7Q++2rfIdjX090s2L+VL+JhuEHiuwzfJi94lut0qpLPtak8d8j3oJedbYy6WNBfbVzrprc0IGEmcyifj7m/7ZXqzU4AdlDjxud1DM=,iv:Qgz1VaYQO9pxohVvZRNE+avZglKWgwoyGBja0l8t3NI=,tag:1Q3PicTgYqjlrUYxKOgz0w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
